services:
  web:
    build: https://github.com/Mubbletm/notification-microservice.git#main
    image: notification-microservice
    ports:
      - "90:8000"
    env_file:
      - ./.env
    environment:
      DATABASE: "mongodb://mongo:27017"
      JWT_SECRET: ${JWT_SECRET}
      PUBLIC_VAPID_KEY: ${PUBLIC_VAPID_KEY}
      PRIVATE_VAPID_KEY: ${PRIVATE_VAPID_KEY}
  mongo:
    image: "mongo:latest"
