name: Deploy
on: [push]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Deploying
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: mkdir -p /opt/deployments/nms/ | docker compose down | 
            cd /opt/deployments/nms && 
            curl https://raw.githubusercontent.com/Mubbletm/notification-microservice/main/docker-compose-actions.yml > docker-compose.yml &&
            echo JWT_SECRET=${{secrets.JWT}} > JWT.env &&
            echo PUBLIC_VAPID_KEY=${{secrets.PUBLIC_VAPID}} > VAPID.pub.env &&
            echo PRIVATE_VAPID_KEY=${{secrets.PRIVATE_VAPID}} > VAPID.env &&
            echo '' > .env &&
            docker compose up -d --no-deps --build
